### ISSUE TITLE
No support for toplevel domains?

### ISSUE THREAD

**Issue by raymonvdm** [sjm-steffann/netbox-ddns#13]
I am trying to use toplevel names for internal DNS zones but it looks like this is not supported. I am using devicename.location. However when i try to recreate DNS records the reverse record gets updated (dns server log also show this) but the forward domain (location) is not

 
```
Nov  6 01:58:35 ns01 pdns_server[1385748]: UPDATE (51429) from x.x.x.x for 168.192.in-addr.arpa: Processing started.
Nov  6 01:58:35 ns01 pdns_server[1385748]: UPDATE (51429) from x.x.x.x for 168.192.in-addr.arpa: starting transaction.
Nov  6 01:58:35 ns01 pdns_server[1385748]: UPDATE (51429) from x.x.x.x for 168.192.in-addr.arpa: Replace for record 252.110.168.192.in-addr.arpa|PTR requested, but no changes made.
Nov  6 01:58:35 ns01 pdns_server[1385748]: UPDATE (51429) from x.x.x.x for 168.192.in-addr.arpa: Update completed, 0 changes, rolling back.
```
Netbox fails with the message

```
Last update	Nov. 6, 2021 12:58 a.m.
Forward DNS	Create: Server not authoritative
Reverse DNS	Create: Success
```

note location.nl as forward DNS is working fine and the pdns database looks good for the "location" zone

**Comment by YWatchman** [comment]
The netbox-ddns plugin uses the resolver of the internal system, which means that the internal resolver should be able to recurse the `.location` zone. Are you sure the Netbox server is able to resolve this?

**Comment by YWatchman** [comment]
@raymonvdm did you manage to resolve this?

**Comment by YWatchman** [comment]
I see, it's checking for a SOA which in fact doesn't exist as this results in an NXDOMAIN.

**Comment by YWatchman** [comment]
It uses the system resolvers, if your system has been setup with resolvers which can find these zones it'll just work.
