### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by ryanmerolle** [sjm-steffann/netbox-ddns#2]
# Feature Request: Publish to PyPi

## Reason:

Publishing to PyPi would allow users to update this plugin using pip & automatically via the NetBox upgrade process when it is added to the local-requirements.txt file in the NetBox directory.

**Comment by steffann** [comment]
You mean this one: https://pypi.org/project/netbox-ddns/ ;)

**Comment by ryanmerolle** [comment]
Ha I did not think to check, I just did not see it in the README.

**Comment by steffann** [comment]
It's hidden in the "add netbox-ddns to your /opt/netbox/local_requirements.txt file" line :)

Cheers!
