### ISSUE TITLE
Pypi release that supports v3.2?

### ISSUE THREAD

**Issue by wmclendon** [sjm-steffann/netbox-ddns#26]
Hello,

I saw that in issue #24 and in PR #25 this plugin was updated to support Netbox v3.2, however it doesn't appear a new pypi release was done, so anyone that just has `netbox-ddns` in their local requirements will fail indicating it only supports v3.1 during the setup.sh run -- at the least, mine did.

For anyone else that runs into this, I was able to fix this by updating my local_requirements.txt file to have this instead:

```
#netbox-ddns
# using this to get the main branch...
git+https://github.com/sjm-steffann/netbox-ddns.git
```

This seems to have resolved my issue -- at the least, Netbox is back up and got no errors with the plugin included!

**Comment by YWatchman** [comment]
Should be fixed in a few.
