### ISSUE TITLE
Add Support for Netbox 3.4

### ISSUE THREAD

**Issue by joek-office** [sjm-steffann/netbox-ddns#32]
Hello,
like a couple of time ago, now i cant use netbox_ddns with Netbox 3.4.
I have installed Netbox 3.4.2 and while running upgrade.sh theres the following message:
`django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.3.999.`

Can you please add support for that version?

**Comment by joek-office** [comment]
Change in Code is done, but i think we need a new tag version.
Have now used the workaround like mentioned here https://github.com/sjm-steffann/netbox-ddns/issues/29#issuecomment-1294194225
Installation is fine

**Comment by YWatchman** [comment]
I pushed a new version release v1.2.6.
