### ISSUE TITLE
Reverse DNS does not update 10.0.0.0/24 against BIND9 DNS

### ISSUE THREAD

**Issue by XPCadmin** [sjm-steffann/netbox-ddns#39]
I see in Netbox Background Tasks that when trying to add a test.mgmt.local 10.0.0.10, the Forward DNS gets updated fine but not the Reverse DNS. It doesn't look like Netbox is trying to add PTR for any 10 networks. Is this a bug or by design?

**Comment by YWatchman** [comment]
It does check if it is authoritative for the zone, if the Netbox server has a local resolver please add the arpa zone to point to your authoritative server. Otherwise this check cannot validate.
