### ISSUE TITLE
Align datetime format with netbox

### ISSUE THREAD

**Issue by blipnet** [sjm-steffann/netbox-ddns#40]
Netbox have a helper called annotated_date that fixes the datetime format.

In netbox_ddns/templates/netbox_ddns/ipaddress/dns_info.html

Add following at top:
`
{% load helpers %}
`

Add the filter where last_updated is printed:

                    <tr>
                        <th scope="row">Last update</th>
                        <td>
                            {{ object.dnsstatus.last_update|annotated_date}}
                        </td>
                    </tr>

Thanks for a really great plugin

**Comment by blipnet** [comment]
Please also change the column type for latest_update in PrefixTable.

File: netbox_ddns/tables.py

Imports will look like this:
```
try:
    # NetBox >= 3.2.0
    from netbox.tables import BaseTable
    from netbox.tables.columns import ToggleColumn, DateTimeColumn
except ImportError:
    # NetBox < 3.2.0
    from utilities.tables import BaseTable, ToggleColumn, DateTimeColumn
```

And under class PrefixTable
```
last_update = DateTimeColumn()
```

**Comment by YWatchman** [comment]
Can you maybe create a pull request including these changes?

**Comment by blipnet** [comment]
I have created a pull request for this change
#43
