### ISSUE TITLE
Does not work with netbox 3.7

### ISSUE THREAD

**Issue by garbled1** [sjm-steffann/netbox-ddns#41]
File "/opt/netbox-3.7.0/netbox/netbox/settings.py", line 798, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/opt/netbox-3.7.0/netbox/netbox/plugins/__init__.py", line 141, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.6.999.

**Comment by Sky-Sail** [comment]
up :+1:

**Comment by Szarky** [comment]
i second this :+1:

**Comment by flyboyjon** [comment]
Me too.  Netbox 3.7.x was released six weeks ago now and we keep tripping over this constraint in netbox_ddns every time there is a major upgrade.  Is there a better, more timely way we can keep this code in step please ?

**Comment by blipnet** [comment]
@YWatchman please merge the PR #42

**Comment by Olling** [comment]
@YWatchman @steffann Are there any plans to fix this, and support Netbox above version 3.6.999?

**Comment by reinoud** [comment]
Is this plugin still maintained?
