### ISSUE TITLE
DDNS server field doesn't accept ipv4 addresses

### ISSUE THREAD

**Issue by nathan-march** [sjm-steffann/netbox-ddns#6]
Trying to add a DDNS server via an ipv4 address right now results in "Enter a valid hostname or IP address"

https://github.com/sjm-steffann/netbox-ddns/blob/d962420de71cc92410ab8226bcd32f65d63f6db4/netbox_ddns/validators.py

ipv6_re is used here, but nothing for ipv4.

**Comment by BouchardClaude** [comment]
I added the ipv4 validator , I think it should work fine with it.  See pull request #15
